# Defs - TLN
### Authors: _Simone Multari_, _Mattia Mondino_, _Loris Signoretti_

In [1]:
from defs_f import *
nltk.download('averaged_perceptron_tagger_eng')

[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger_eng is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger_eng is already up-to-
[nltk_data]       date!

True

In [2]:
stemmer = porter.PorterStemmer()
lemmatizer = WordNetLemmatizer()

#### Dataset
Caricamento del dataset e creazione di due dataset normalizzati, uno che utilizza lo Stemming e l'altro che utilizza il Lemmatization.

In [3]:
dataset = pd.read_csv("TLN-definitions-24.csv", sep=",")
#remove first column
dataset = dataset.iloc[:, 1:]

dataset_lem = dataset.map(lambda s: lemmatize_sentence(s))

dataset = dataset.map(lambda s: remove_stopwords(s))

dataset_stem = dataset.map(lambda s: " ".join([stemmer.stem(word) for word in word_tokenize(s)]))
dataset_lem = dataset_lem.map(lambda s: remove_stopwords(s))

dataset_stem.head()

,pen,cigarette,cloud,ontology
0,object use write paper fill ink,object fill mainli bu tobacco smoke pleasur,atmospher phenomenon,philosoph studi natur structur be realiti cate...
1,object use write peper,cylind paper tobacco insid,specif atmospher condit,field philosophi use univers univers
2,a pen tool use write paper use ink,a cigarett object smoke pleasur,a cloud white sky object respons rain,a ontolog tool use creat common knowledg diffe...
3,a pen object use write ink,a cigarett object contain tobacco it use smoke,a cloud mass water drop atmospher witch take d...,an ontolog method repres knowledg
4,an object use write paper usual tool permit sp...,a product made tobacco insert paper could made...,the format sky deriv condens water particl atm...,the scienc studi carachterist relat exist it p...

#### Similarity

Calcolo, per ogni termine, della similarità delle difinizioni per i due dataset, normalizzata secondo la lunghezza massima delle definizioni.

In [4]:
scores_stem = []
for word in dataset_stem.columns.values:
    word_scores = [calculate_def_similarity(def1, def2) for def1 in dataset_stem[word] for def2 in dataset_stem[word] if id(def1) < id(def2)]
    scores_stem.append(word_scores)

scores_lem = []
for word in dataset_lem.columns.values:
    word_scores = [calculate_def_similarity(def1, def2) for def1 in dataset_lem[word] for def2 in dataset_lem[word] if id(def1) < id(def2)]
    scores_lem.append(word_scores)

### Score
Lo score viene calcolato effettuando una media dei punteggi di similarità per ogni termine.

Stemming Score:

In [5]:
df_score_stem = pd.DataFrame(index=dataset_stem.columns.values, columns=['score'])
df_score_stem['score'] = [sum(word_scores) / len(word_scores) for word_scores in scores_stem]
df_score_stem

              score
pen        0.570749
cigarette  0.376413
cloud      0.199291
ontology   0.155347

Lemming Score:

In [6]:
df_score_lem = pd.DataFrame(index=dataset_lem.columns.values, columns=['score'])
df_score_lem['score'] = [sum(word_scores) / len(word_scores) for word_scores in scores_lem]
df_score_lem

              score
pen        0.569691
cigarette  0.354588
cloud      0.147253
ontology   0.125779