In [1]:
import pandas as pd
from collections import defaultdict, Counter
import nltk
from nltk.tokenize import word_tokenize
import numpy as np

In [13]:
df = pd.read_csv('data/tweets.csv')
df.head()

,source,text,created_at,retweet_count,favorite_count,is_retweet,id_str
0,Twitter for iPhone,LOSER! https://t.co/p5imhMJqS1,05-18-2020 14:55:14,32295,135445,False,1262396333064892416
1,Twitter for iPhone,Most of the money raised by the RINO losers of...,05-05-2020 18:18:26,19706,82425,False,1257736426206031874
2,Twitter for iPhone,....because they don’t know how to win and the...,05-05-2020 04:46:34,12665,56868,False,1257532112233803782
3,Twitter for iPhone,....lost for Evan “McMuffin” McMullin (to me)....,05-05-2020 04:46:34,13855,62268,False,1257532114666508291
4,Twitter for iPhone,....get even for all of their many failures. Y...,05-05-2020 04:46:33,8122,33261,False,1257532110971318274

In [14]:
def preprocessing(text):
    words = word_tokenize(text)
    filtered_words = []
    for word in words:
        print(word)
        if word == "&":
            filtered_words.append("and")
        if word == "amp":
            continue

        #puntuation
        if word in ['.', ',', '!', '?', ';', ':']:
            filtered_words.append(word)
        elif word.isalpha():
            filtered_words.append(word.lower())
        elif word.isalnum():
            filtered_words.append(word)
        
    return ['<s>'] + filtered_words + ['</s>']

preprocessing("I have always liked &amp; respected")

I
have
always
liked
&
amp
;
respected

['<s>', 'i', 'have', 'always', 'liked', 'and', ';', 'respected', '</s>']

In [15]:
df['tokens'] = df['text'].apply(preprocessing)
df.head()

LOSER
!
https
:
//t.co/p5imhMJqS1
Most
of
the
money
raised
by
the
RINO
losers
of
the
so-called
“
Lincoln
Project
”
goes
into
their
own
pockets
.
With
what
I
’
ve
done
on
Judges
Taxes
Regulations
Healthcare
the
Military
Vets
(
Choice
!
)
&
amp
;
protecting
our
great
2A
they
should
love
Trump
.
Problem
is
I
BEAT
THEM
ALL
!
....
because
they
don
’
t
know
how
to
win
and
their
so-called
Lincoln
Project
is
a
disgrace
to
Honest
Abe
.
I
don
’
t
know
what
Kellyanne
did
to
her
deranged
loser
of
a
husband
Moonface
but
it
must
have
been
really
bad
.
John
Weaver
lost
big
for
Kasich
(
to
me
)
.
Crazed
Rick
Wilson
....
....
lost
for
Evan
“
McMuffin
”
McMullin
(
to
me
)
.
Steve
Schmidt
&
amp
;
Reed
Galvin
lost
for
John
McCain
Romney
’
s
campaign
manager
(
?
)
lost
big
to
“
O
”
&
amp
;
Jennifer
Horn
got
thrown
out
of
the
New
Hampshire
Republican
Party
.
They
’
re
all
LOSERS
but
Abe
Lincoln
Republican
is
all
smiles
!
....
get
even
for
all
of
their
many
failures
.
You
see
these
loser
types
don
’
t
care
about
252
new
Federal
Judges
2
great
Supreme
Court
Justices
a
rebuilt
military
a
protected
2nd
Amendment
biggest
EVER
Tax
&
amp
;
Regulation
cuts
and
much
more
.
I
didn
’
t
use
any
of
them
....
Cryin
Chuck
Schumer
compared
to
what
other
Senators
have
brought
home
to
their
states
has
brought
very
little
back
to
N.Y.
A
totally
overrated
loser
the
one
thing
he
has
given
them
is
SALT
.
He
never
even
called
me
to
stop
it
.
No
wonder
Cuomo
&
amp
;
most
others
can
’
t
stand
him
.
AOC
!
They
are
Fake
News
Losers
!
https
:
//t.co/3RHcBZogms
The
Wall
Street
Journal
Editorial
Board
doesn
’
t
have
a
clue
on
how
to
fight
and
win
.
Their
views
on
Tariffs
&
amp
;
Trade
are
losers
for
the
U.S.
but
winners
for
other
countries
including
China
.
If
we
followed
their
standards
we
’
d
have
no
Country
left
.
They
should
love
Sleepy
Joe
!
Pocahontas
working
in
conjunction
with
the
Democrat
Party
totally
destroyed
the
campaign
of
Bernie
Sanders
.
If
she
would
have
quit
3
days
earlier
Sanders
would
have
beaten
Biden
in
a
route
it
wouldn
’
t
even
have
been
close
.
They
also
got
two
other
losers
to
support
Sleepy
Joe
!
Elizabeth
“
Pocahontas
”
Warren
other
than
Mini
Mike
was
the
loser
of
the
night
.
She
didn
’
t
even
come
close
to
winning
her
home
state
of
Massachusetts
.
Well
now
she
can
just
sit
back
with
her
husband
and
have
a
nice
cold
beer
!
The
biggest
loser
tonight
by
far
is
Mini
Mike
Bloomberg
.
His
“
political
”
consultants
took
him
for
a
ride
.
$
700
million
washed
down
the
drain
and
he
got
nothing
for
it
but
the
nickname
Mini
Mike
and
the
complete
destruction
of
his
reputation
.
Way
to
go
Mike
!
A
so-called
reporter
named
@
JohnJHarwood
who
bombed
so
badly
in
the
2016
Presidential
Debates
that
I
thought
he
was
going
to
be
immediately
fired
(
a
Mini
Mike
type
performance
)
is
now
with
Fake
News
@
CNN
.
A
total
loser
!
To
the
people
of
South
Carolina
Tom
Steyer
is
a
joke
laughed
at
by
everyone
a
total
incompetent
.
He
made
money
in
coal
now
he
“
hates
”
coal
.
Did
you
see
him
fawning
over
Crazy
Bernie
?
Has
no
chance
a
loser
for
South
Carolina
doesn
’
t
deserve
your
vote
!
RT
@
ByronYork
:
Amusing
:
First
Bloomberg
called
for
Biden
Buttigieg
Klobuchar
to
quit
race
.
Hey
all
you
losers
leave
it
to
Mike
!
Now
Te…
Mini
Mike
Bloomberg
is
a
LOSER
who
has
money
but
can
’
t
debate
and
has
zero
presence
you
will
see
.
He
reminds
me
of
a
tiny
version
of
Jeb
“
Low
Energy
”
Bush
but
Jeb
has
more
political
skill
and
has
treated
the
Black
community
much
better
than
Mini
!
https
:
//t.co/qIef5VhjDr
Steyer
is
a
major
loser
.
Just
doesn
’
t
get
it
.
This
is
second
time
with
Bernie
!
https
:
//t.co/fxZh8zNhks
Two
stone
cold
losers
from
Amazon
WP
.
Almost
every
story
is
a
made
up
lie
just
like
corrupt
pol
Shifty
Schiff
who
fraudulently
made
up
my
call
with
Ukraine
.
Fiction
!
https
:
//t.co/0Oad0738NG
RT
@
RepMattGaetz
:
There
are
a
lot
of
moderate
Dems
who
recognize
what
a
political
loser
impeachment
is.They
're
encouraging
their
leadersh…
Don
’
t
get
why
@
FoxNews
puts
losers
on
like
@
RepSwalwell
(
who
got
ZERO
as
presidential
candidate
before
quitting
)
Pramila
Jayapal
David
Cicilline
and
others
who
are
Radical
Left
Haters
?
The
Dems
wouldn
’
t
let
@
FoxNews
get
near
their
bad
ratings
debates
yet
Fox
panders
.
Pathetic
!
Why
do
@
ShannonBream
&
amp
;
@
FoxNews
waste
airtime
on
Democrat
Rep.
Eric
Swalwell
who
recently
left
the
Presidential
Primaries
having
attained
a
grand
number
of
ZERO
in
the
polls
.
I
don
’
t
even
know
how
that
is
possible
.
Fox
should
stay
with
the
people
that
got
them
there
not
losers
!
“
Nancy
Pelosi
cares
more
about
power
than
she
does
about
principle
.
She
did
not
want
to
go
down
this
road
.
She
realizes
this
is
a
huge
loser
for
Democrats
.
The
Founders
envisioned
the
worst
people
being
in
politics
yet
they
couldn
’
t
envision
this
.
You
have
these
people
taking
...
But
the
Witch
Hunt
continues
.
After
3
years
of
relentless
attacks
against
the
Republican
Party
&
amp
;
me
the
Do
Nothing
Dems
are
losers
for
America
!
https
:
//t.co/met2y8VoPe
Who
the
hell
is
Joy-Ann
Reid
?
Never
met
her
she
knows
ZERO
about
me
has
NO
talent
and
truly
doesn
’
t
have
the
“
it
”
factor
needed
for
success
in
showbiz
.
Had
a
bad
reputation
and
now
works
for
the
Comcast/NBC
losers
making
up
phony
stories
about
me
.
Low
Ratings
.
Fake
News
!
A
made
up
Radical
Left
Story
about
Doral
bedbugs
but
Bret
Stephens
is
loaded
up
with
them
!
Been
calling
me
wrong
for
years
along
with
the
few
remaining
Never
Trumpers
-
All
Losers
!
https
:
//t.co/KlzzMC40Vt
Just
watched
a
world
class
loser
Tim
O
’
Brien
who
I
haven
’
t
seen
or
spoken
to
in
many
years
&
amp
;
knows
NOTHING
about
me
except
that
he
wrote
a
failed
hit
piece
book
about
me
15
years
ago
.
Fired
like
a
dog
from
other
jobs
?
Saw
him
on
Lyin
’
Brian
Williams
Trump
Slam
Show
.
Bad
TV
....
....
I
am
so
amazed
that
MSNBC
&
amp
;
CNN
can
keep
putting
on
over
and
over
again
people
that
have
no
idea
what
I
am
all
about
and
yet
they
speak
as
experts
on
“
Trump.
”
Same
people
since
long
before
the
2016
Election
and
how
did
that
work
out
for
the
Haters
and
Losers
.
Not
well
!
Great
news
for
the
Republican
Party
as
one
of
the
dumbest
&
amp
;
most
disloyal
men
in
Congress
is
“
quitting
”
the
Party
.
No
Collusion
No
Obstruction
!
Knew
he
couldn
’
t
get
the
nomination
to
run
again
in
the
Great
State
of
Michigan
.
Already
being
challenged
for
his
seat
.
A
total
loser
!
RT
@
RealCandaceO
:
You
can
not
be
a
victim
and
a
victor
at
the
same
time
.
You
can
either
choose
to
win
or
accept
your
status
as
a
loser.…
Big
Rally
tomorrow
night
in
Orlando
Florida
looks
to
be
setting
records
.
We
are
building
large
movie
screens
outside
to
take
care
of
everybody
.
Over
100000
requests
.
Our
Country
is
doing
great
far
beyond
what
the
haters
&
amp
;
losers
thought
possible
-
and
it
will
only
get
better
!
The
Corrupt
News
Media
is
totally
out
of
control
-
they
have
given
up
and
don
’
t
even
care
anymore
.
Mainstream
Media
has
ZERO
CREDIBILITY
-
TOTAL
LOSERS
!
....
other
than
to
know
he
was
and
is
a
total
Loser
.
When
he
makes
statements
about
me
they
are
made
up
he
knows
nothing
!
.
@
SadiqKhan
who
by
all
accounts
has
done
a
terrible
job
as
Mayor
of
London
has
been
foolishly
“
nasty
”
to
the
visiting
President
of
the
United
States
by
far
the
most
important
ally
of
the
United
Kingdom
.
He
is
a
stone
cold
loser
who
should
focus
on
crime
in
London
not
me
......
....
he
would
see
that
it
was
nevertheless
strong
on
NO
COLLUSION
and
ultimately
NO
OBSTRUCTION
...
Anyway
how
do
you
Obstruct
when
there
is
no
crime
and
in
fact
the
crimes
were
committed
by
the
other
side
?
Justin
is
a
loser
who
sadly
plays
right
into
our
opponents
hands
!
....
There
is
nothing
to
admire
about
them
they
will
always
try
to
show
a
glimmer
of
vicious
hope
but
they
are
losers
and
barely
breathing
.
Think
about
that
before
you
destroy
your
lives
and
the
lives
of
your
family
!
George
Conway
often
referred
to
as
Mr.
Kellyanne
Conway
by
those
who
know
him
is
VERY
jealous
of
his
wife
’
s
success
&
amp
;
angry
that
I
with
her
help
didn
’
t
give
him
the
job
he
so
desperately
wanted
.
I
barely
know
him
but
just
take
a
look
a
stone
cold
LOSER
&
amp
;
husband
from
hell
!
A
total
loser
!
https
:
//t.co/vm3Vv2f9jf
RT
@
vmbb12
:
We
have
to
fight
back
.
They
have
not
let
up
on
President
Trump
nor
his
supporters
since
they
lost
.
They
are
losers
we
are
win…
....
must
stay
strong
and
fight
back
with
vigor
.
Stop
working
soooo
hard
on
being
politically
correct
which
will
only
bring
you
down
and
continue
to
fight
for
our
Country
.
The
losers
all
want
what
you
have
don
’
t
give
it
to
them
.
Be
strong
&
amp
;
prosper
be
weak
&
amp
;
die
!
Stay
true
....
“
Now
that
the
Dems
are
going
to
try
&
amp
;
switch
from
Collusion
to
some
other
reason
it
makes
them
continue
to
look
like
sore
losers
who
didn
’
t
accept
the
WILL
OF
THE
PEOPLE
in
the
last
election
-
they
will
do
anything
to
get
rid
of
the
President.
”
@
AriFleischer
It
will
never
work
!
I
never
said
anything
bad
about
Andrew
McCabe
’
s
wife
other
than
she
(
they
)
should
not
have
taken
large
amounts
of
campaign
money
from
a
Crooked
Hillary
source
when
Clinton
was
under
investigation
by
the
FBI
.
I
never
called
his
wife
a
loser
to
him
(
another
McCabe
made
up
lie
)
!
Lyin
’
James
Comey
Andrew
McCabe
Peter
S
and
his
lover
agent
Lisa
Page
&
amp
;
more
all
disgraced
and/or
fired
and
caught
in
the
act
.
These
are
just
some
of
the
losers
that
tried
to
do
a
number
on
your
President
.
Part
of
the
Witch
Hunt
.
Remember
the
“
insurance
policy
?
”
This
is
it
!
How
can
“
Senator
”
Richard
Blumenthal
who
went
around
for
twenty
years
as
a
Connecticut
politician
bragging
that
he
was
a
great
Marine
war
hero
in
Vietnam
(
then
got
caught
and
sobbingly
admitted
he
was
neither
a
Marine
nor
ever
in
Vietnam
)
pass
judgement
on
anyone
?
Loser
!
...
really
bad
things
.
Nasty
to
people
&
amp
;
would
constantly
miss
meetings
&
amp
;
work
.
When
Gen.
Kelly
came
on
board
he
told
me
she
was
a
loser
&
amp
;
nothing
but
problems
.
I
told
him
to
try
working
it
out
if
possible
because
she
only
said
GREAT
things
about
me
-
until
she
got
fired
!
.....
Will
the
FBI
ever
recover
it
’
s
once
stellar
reputation
so
badly
damaged
by
Comey
McCabe
Peter
S
and
his
lover
the
lovely
Lisa
Page
and
other
top
officials
now
dismissed
or
fired
?
So
many
of
the
great
men
and
women
of
the
FBI
have
been
hurt
by
these
clowns
and
losers
!
.....
Will
the
FBI
ever
recover
it
’
s
once
stellar
reputation
so
badly
damaged
by
Comey
McCabe
Peter
S
and
his
lover
the
lovely
Lisa
Page
and
other
top
officials
now
dismissed
or
fired
?
So
many
of
the
great
men
and
women
of
the
FBI
have
been
hurt
by
these
clowns
and
losers
!
Why
was
the
FBI
’
s
sick
loser
Peter
Strzok
working
on
the
totally
discredited
Mueller
team
of
13
Angry
&
amp
;
Conflicted
Democrats
when
Strzok
was
giving
Crooked
Hillary
a
free
pass
yet
telling
his
lover
lawyer
Lisa
Page
that
“
we
’
ll
stop
”
Trump
from
becoming
President
?
Witch
Hunt
!
The
fact
that
I
am
having
a
meeting
is
a
major
loss
for
the
U.S.
say
the
haters
&
amp
;
losers
.
We
have
our
hostages
testing
research
and
all
missle
launches
have
stoped
and
these
pundits
who
have
called
me
wrong
from
the
beginning
have
nothing
else
they
can
say
!
We
will
be
fine
!
....
non-existent
“
sources
”
and
a
drunk/drugged
up
loser
who
hates
Michael
a
fine
person
with
a
wonderful
family
.
Michael
is
a
businessman
for
his
own
account/lawyer
who
I
have
always
liked
&
amp
;
respected
.
Most
people
will
flip
if
the
Government
lets
them
out
of
trouble
even
if
....
....
non-existent
“
sources
”
and
a
drunk/drugged
up
loser
who
hates
Michael
a
fine
person
with
a
wonderful
family
.
Michael
is
a
businessman
for
his
own
account/lawyer
who
I
have
always
liked
&
amp
;
respected
.
Most
people
will
flip
if
the
Government
lets
them
out
of
trouble
even
if
....
The
Fake
News
of
big
ratings
loser
CNN
.
https
:
//t.co/rYsv90cnvs
The
Democrats
want
to
shut
down
the
Government
over
Amnesty
for
all
and
Border
Security
.
The
biggest
loser
will
be
our
rapidly
rebuilding
Military
at
a
time
we
need
it
more
than
ever
.
We
need
a
merit
based
system
of
immigration
and
we
need
it
now
!
No
more
dangerous
Lottery
.
The
Fake
News
Awards
those
going
to
the
most
corrupt
&
amp
;
biased
of
the
Mainstream
Media
will
be
presented
to
the
losers
on
Wednesday
January
17th
rather
than
this
coming
Monday
.
The
interest
in
and
importance
of
these
awards
is
far
greater
than
anyone
could
have
anticipated
!
Michael
Wolff
is
a
total
loser
who
made
up
stories
in
order
to
sell
this
really
boring
and
untruthful
book
.
He
used
Sloppy
Steve
Bannon
who
cried
when
he
got
fired
and
begged
for
his
job
.
Now
Sloppy
Steve
has
been
dumped
like
a
dog
by
almost
everyone
.
Too
bad
!
https
:
//t.co/mEeUhk5ZV9
Crooked
Hillary
Clinton
is
the
worst
(
and
biggest
)
loser
of
all
time
.
She
just
can
’
t
stop
which
is
so
good
for
the
Republican
Party
.
Hillary
get
on
with
your
life
and
give
it
another
try
in
three
years
!
While
in
the
Philippines
I
was
forced
to
watch
@
CNN
which
I
have
not
done
in
months
and
again
realized
how
bad
and
FAKE
it
is
.
Loser
!
RT
@
realDonaldTrump
:
Loser
terrorists
must
be
dealt
with
in
a
much
tougher
manner.The
internet
is
their
main
recruitment
tool
which
we
must…
Loser
terrorists
must
be
dealt
with
in
a
much
tougher
manner.The
internet
is
their
main
recruitment
tool
which
we
must
cut
off
&
amp
;
use
better
!
Another
attack
in
London
by
a
loser
terrorist.These
are
sick
and
demented
people
who
were
in
the
sights
of
Scotland
Yard
.
Must
be
proactive
!
RT
@
Bet22325450ste
:
@
FoxBusiness
@
foxandfriends
Come
on
America
.
Get
on
the
Trump
Train
.
The
winners
already
have
boarded
!
The
losers
are
w…
.
@
CNN
just
does
n't
get
it
and
that
's
why
their
ratings
are
so
low
-
and
getting
worse
.
Boring
anti-Trump
panelists
mostly
losers
in
life
!
Bill
Kristol
has
been
wrong
for
2yrs-an
embarrassed
loser
but
if
the
GOP
ca
n't
control
their
own
then
they
are
not
a
party
.
Be
tough
R
's
!
@
daybastrop
@
foxandfriends
@
BretBaier
The
liars
that
signed
the
pledge
and
now
wo
n't
support
@
realDonaldTrump
IS
the
reason
they
are
losers,05-09-2016
12:15:04,3520,10096
,
false,729645861089775616
Twitter
for
iPhone
,
Phony
Club
For
Growth
tried
to
shake
me
down
for
one
million
dollars
&
amp
;
is
now
putting
out
nasty
negative
ads
on
me
.
They
are
total
losers
!
,03-09-2016
21:46:12,4856,13859
,
false,707683931609550848
Twitter
for
Android
,
.
@
FoxNews
is
devastated
that
lightweight
Senator
Marco
Rubio
got
trounced
tonight
and
is
the
big
loser
.
I
won
the
two
big
states
great
!
,03-06-2016
05:40:37,5472,19409
,
false,706353772751163392
Twitter
for
Android
,
@
SirHatchporch
:
Mary
Kissel
is
an
SNL
character
right
?
She
's
not
a
real
person
right
?
#
MorningJoe
''
She
is
a
major
loser
-
no
clue
!
Have
a
good
chance
to
win
Texas
on
Tuesday
.
Cruz
is
a
nasty
guy
not
one
Senate
endorsement
and
despite
talk
gets
nothing
done
.
Loser
!
There
are
no
buyers
for
the
worthless
@
NYDailyNews
but
little
Mort
Zuckerman
is
frantically
looking
.
It
is
bleeding
red
ink
-
a
total
loser
!
Really
dumb
@
CheriJacobus
.
Begged
my
people
for
a
job
.
Turned
her
down
twice
and
she
went
hostile
.
Major
loser
zero
credibility
!
Dope
Frank
Bruni
said
I
called
many
people
including
Karl
Rove
losers-true
!
I
never
called
my
friend
@
HowardStern
a
loser-
he
’
s
a
winner
!
Joe
McQuaid
(
@
deucecrew
)
is
desperately
trying
to
sell
the
@
UnionLeader
.
It
's
a
loser
and
my
comments
have
n't
helped
him
much
.
@
Sir_Max
:
andreajmarkley
:
Rubio
finally
gets
an
endorsement
–
from
#
Benghazi
loser
Gowdy
#
Tcot
#
pjnet
https
:
//t.co/lJcHG0IHaM
via
dailyne,12-27-2015
12:37:24,929,2210
,
false,681091509811306496
Twitter
for
Android
,
.
@
JebBush
today
said
he
did
n't
want
to
be
the
front-runner
he
would
rather
be
where
he
is
now
2
%
.
That
is
the
talk
of
a
loser
ca
n't
win
!
,12-21-2015
04:42:21,3119,8076
,
false,678797631250911232
Twitter
for
Android
,
Something
must
be
done
with
dopey
@
KarlRove
-
he
is
pushing
Republicans
down
the
same
old
path
of
defeat
.
Do
n't
fall
for
it
Karl
is
a
loser,12-13-2015
05:28:50,2528,6031
,
false,675910224855855104
Twitter
for
Android
,
Why
does
@
CNN
bore
their
audience
with
people
like
@
secupp
a
totally
biased
loser
who
does
n't
have
a
clue
.
I
hear
she
will
soon
be
gone
!
,12-10-2015
02:25:58,1471,4041
,
false,674777043163332608
Twitter
for
Android
,
@
mysteriousLoser
:
@
realDonaldTrump
did
you
hear
the
mayor
nutter
of
philadelphias
comments
towards
you
?
Ignorance
''
Yes
he
is
a
crude
dope
!
@
KarlRove
just
totally
bombed
on
@
Morning_Joe
.
@
FoxNews
has
him
on
even
though
he
has
lost
all
credibility
-
a
loser
!
Fox
should
dump
Rove
.
Republicans
must
stop
relying
on
losers
like
@
KarlRove
if
they
want
to
start
winning
presidential
elections
.
Be
tough
and
get
smart
!
The
media
must
immediately
stop
calling
ISIS
leaders
``
MASTERMINDS
.
''
Call
them
instead
thugs
and
losers
.
Young
people
must
not
go
into
ISIS
!
I
have
watched
sloppy
Graydon
Carter
fail
and
close
Spy
Magazine
and
now
am
watching
him
fail
at
@
VanityFair
Magazine
.
He
is
a
total
loser
!
@
N_R_Mandela
:
@
realDonaldTrump
And
you
're
still
a
negative
loser
and
Trump
is
still
a
positive
winner
.
I
'm
Black
and
proudly
voting
TRUMP
!
The
money
losing
@
politico
is
considered
by
many
in
the
world
of
politics
to
be
the
dumbest
and
most
slanted
of
the
political
sites
.
Losers
!
@
joeoh89
:
@
seanhannity
@
realDonaldTrump
What
happened
to
The
Pledge
?
Walker
quits
and
slams
Trump
.
Losers
proving
Pledge
was
sham
.
@
MlSSTHOT
:
@
realDonaldTrump
:
Ignore
the
losers
and
the
haters
you
are
going
to
make
this
country
great
again
@
RubenMMoreno
:
@
realDonaldTrump
The
biggest
loser
in
the
debate
was
@
megynkelly
.
You
ca
n't
out
trump
Donald
Trump
.
You
will
lose
!
,08-07-2015
07:23:31,866,1977
,
false,629553442944602112
Twitter
Web
Client
,
Via
@
fitsnews
:
“
Donald
Trump
:
John
McCain
Is
‘
A
Loser
’
”
http
:
//t.co/sgiETvdUqi,07-18-2015
21:45:48,438,905
,
false,622522682245033984
Twitter
Web
Client
,
.
@
KarlRove
wasted
$
400
million
+
and
didn
’
t
win
one
race—a
total
loser
.
@
FoxNews,07-16-2015
15:02:34,537,845
,
false,621696429749325825
Twitter
for
Android
,
@
nojoed
:
@
realDonaldTrump
@
KarlRove
Karl
why
do
n't
you
sit
this
election
cycle
out
we
had
enough
losers
to
last
us
a
life
time
.
''
True
.
It
's
time
for
government
to
stop
picking
winners
&
amp
;
losers
.
Let
’
s
make
sure
everyone
can
achieve
the
American
dream
!
https
:
//t.co/u25yI5T7E8
@
_Snurk
:
@
realDonaldTrump
Love
it
!
Always
respect
FIGHTERS
over
overrated
loser
POLITITIANS
!
!
Inspire
GREATNESS
!
#
TRUMP
#
2016
@
Bobzilla305
:
@
realDonaldTrump
@
krauthammer
is
a
progressive
making
money
off
of
the
Conservative
viewership
A
total
loser
!
All
the
haters
&
amp
;
losers
must
admit
that
unlike
others
I
never
attacked
dopey
Jon
Stewart
for
his
phony
last
name
.
Would
never
do
that
!
While
Jon
Stewart
is
a
joke
not
very
bright
and
totally
overrated
some
losers
and
haters
will
miss
him
&
amp
;
his
dumb
clown
humor
.
Too
bad
!
All
the
haters
and
losers
must
admit
that
unlike
others
I
never
attacked
dopey
Jon
Stewart
for
his
phony
last
name
.
Would
never
do
that
!
While
Jon
Stewart
is
a
joke
not
very
bright
and
totally
overrated
some
losers
and
haters
will
miss
him
and
his
dumb
clown
humor
.
Too
bad
!
I
would
like
to
wish
everyone
including
all
haters
and
losers
(
of
which
sadly
there
are
many
)
a
truly
happy
and
enjoyable
Memorial
Day
!
@
HarmonBrew
:
@
FoxNews
@
megynkelly
DonaldTrump
#
KellyFile
Trump
is
so
right
about
Geller
.
Megyn
stop
advocating
for
her
;
its
a
loser
.
@
KhathuEnos
ignoring
haters
and
losers
is
the
best
medicine
of
success
build
a
wall
from
whatever
they
throw
towards
you
Sir
.
@
utkarsh_chheda
:
@
realDonaldTrump
@
Elgianne
damn
..
a
lot
of
haters
follow
u
....
Haters
and
losers
!
Why
do
we
always
try
to
destroy
our
true
champions
and
winners
in
this
country
while
at
the
same
time
leaving
the
losers
alone
?
STUPID
!
@
ScottFConroy
:
Kentucky
Derby
?
More
like
Kentucky
Losers
!
DonaldTrump
is
only
horse
in
race
that

,source,text,created_at,retweet_count,favorite_count,is_retweet,id_str,tokens
0,Twitter for iPhone,LOSER! https://t.co/p5imhMJqS1,05-18-2020 14:55:14,32295,135445,False,1262396333064892416,"[<s>, loser, !, https, :, </s>]"
1,Twitter for iPhone,Most of the money raised by the RINO losers of...,05-05-2020 18:18:26,19706,82425,False,1257736426206031874,"[<s>, most, of, the, money, raised, by, the, r..."
2,Twitter for iPhone,....because they don’t know how to win and the...,05-05-2020 04:46:34,12665,56868,False,1257532112233803782,"[<s>, because, they, don, t, know, how, to, wi..."
3,Twitter for iPhone,....lost for Evan “McMuffin” McMullin (to me)....,05-05-2020 04:46:34,13855,62268,False,1257532114666508291,"[<s>, lost, for, evan, mcmuffin, mcmullin, to,..."
4,Twitter for iPhone,....get even for all of their many failures. Y...,05-05-2020 04:46:33,8122,33261,False,1257532110971318274,"[<s>, get, even, for, all, of, their, many, fa..."

In [16]:
word_counts = Counter()
for tokens in df['tokens']:
    word_counts.update(tokens)

word_counts.most_common(10)

[('.', 291),
 ('<s>', 261),
 ('</s>', 261),
 ('the', 248),
 ('and', 218),
 ('a', 213),
 ('!', 207),
 ('losers', 136),
 ('loser', 135),
 ('is', 124)]

In [17]:
for tokens in df['tokens'].iloc[:2]:
    print(tokens[:-1])
    print(tokens[1:])
    x = zip(tokens[:-1], tokens[1:])
    print(list(x))
    print()

['<s>', 'loser', '!', 'https', ':']
['loser', '!', 'https', ':', '</s>']
[('<s>', 'loser'), ('loser', '!'), ('!', 'https'), ('https', ':'), (':', '</s>')]

['<s>', 'most', 'of', 'the', 'money', 'raised', 'by', 'the', 'rino', 'losers', 'of', 'the', 'lincoln', 'project', 'goes', 'into', 'their', 'own', 'pockets', '.', 'with', 'what', 'i', 've', 'done', 'on', 'judges', 'taxes', 'regulations', 'healthcare', 'the', 'military', 'vets', 'choice', '!', 'and', ';', 'protecting', 'our', 'great', '2A', 'they', 'should', 'love', 'trump', '.', 'problem', 'is', 'i', 'beat', 'them', 'all', '!']
['most', 'of', 'the', 'money', 'raised', 'by', 'the', 'rino', 'losers', 'of', 'the', 'lincoln', 'project', 'goes', 'into', 'their', 'own', 'pockets', '.', 'with', 'what', 'i', 've', 'done', 'on', 'judges', 'taxes', 'regulations', 'healthcare', 'the', 'military', 'vets', 'choice', '!', 'and', ';', 'protecting', 'our', 'great', '2A', 'they', 'should', 'love', 'trump', '.', 'problem', 'is', 'i', 'beat', 'them', 'all', '!', '</s>']
[('<s>', 'most'), ('most', 'of'), ('of', 'the'), ('the', 'money'), ('money', 'raised'), ('raised', 'by'), ('by', 'the'), ('the', 'rino'), ('rino', 'losers'), ('losers', 'of'), ('of', 'the'), ('the', 'lincoln'), ('lincoln', 'project'), ('project', 'goes'), ('goes', 'into'), ('into', 'their'), ('their', 'own'), ('own', 'pockets'), ('pockets', '.'), ('.', 'with'), ('with', 'what'), ('what', 'i'), ('i', 've'), ('ve', 'done'), ('done', 'on'), ('on', 'judges'), ('judges', 'taxes'), ('taxes', 'regulations'), ('regulations', 'healthcare'), ('healthcare', 'the'), ('the', 'military'), ('military', 'vets'), ('vets', 'choice'), ('choice', '!'), ('!', 'and'), ('and', ';'), (';', 'protecting'), ('protecting', 'our'), ('our', 'great'), ('great', '2A'), ('2A', 'they'), ('they', 'should'), ('should', 'love'), ('love', 'trump'), ('trump', '.'), ('.', 'problem'), ('problem', 'is'), ('is', 'i'), ('i', 'beat'), ('beat', 'them'), ('them', 'all'), ('all', '!'), ('!', '</s>')]

In [18]:
bigram_counts = defaultdict(Counter)
for tokens in df['tokens']:
    for token1, token2 in zip(tokens[:-1], tokens[1:]): 
        bigram_counts[token1].update([token2])

bigram_counts['<s>'].most_common(10)

[('i', 18),
 ('the', 16),
 (':', 13),
 ('.', 11),
 ('why', 7),
 ('rt', 6),
 ('it', 5),
 ('lightweight', 5),
 ('a', 4),
 ('happy', 4)]

In [19]:
for tokens in df['tokens'].iloc[:2]:
    print(tokens[:-2])
    print(tokens[1:-1]) # skip the first token and the last token
    print(tokens[2:]) # skip the first two tokens
    x = zip(tokens[:-2], tokens[1:-1], tokens[2:])
    print(list(x))
    print()

['<s>', 'loser', '!', 'https']
['loser', '!', 'https', ':']
['!', 'https', ':', '</s>']
[('<s>', 'loser', '!'), ('loser', '!', 'https'), ('!', 'https', ':'), ('https', ':', '</s>')]

['<s>', 'most', 'of', 'the', 'money', 'raised', 'by', 'the', 'rino', 'losers', 'of', 'the', 'lincoln', 'project', 'goes', 'into', 'their', 'own', 'pockets', '.', 'with', 'what', 'i', 've', 'done', 'on', 'judges', 'taxes', 'regulations', 'healthcare', 'the', 'military', 'vets', 'choice', '!', 'and', ';', 'protecting', 'our', 'great', '2A', 'they', 'should', 'love', 'trump', '.', 'problem', 'is', 'i', 'beat', 'them', 'all']
['most', 'of', 'the', 'money', 'raised', 'by', 'the', 'rino', 'losers', 'of', 'the', 'lincoln', 'project', 'goes', 'into', 'their', 'own', 'pockets', '.', 'with', 'what', 'i', 've', 'done', 'on', 'judges', 'taxes', 'regulations', 'healthcare', 'the', 'military', 'vets', 'choice', '!', 'and', ';', 'protecting', 'our', 'great', '2A', 'they', 'should', 'love', 'trump', '.', 'problem', 'is', 'i', 'beat', 'them', 'all', '!']
['of', 'the', 'money', 'raised', 'by', 'the', 'rino', 'losers', 'of', 'the', 'lincoln', 'project', 'goes', 'into', 'their', 'own', 'pockets', '.', 'with', 'what', 'i', 've', 'done', 'on', 'judges', 'taxes', 'regulations', 'healthcare', 'the', 'military', 'vets', 'choice', '!', 'and', ';', 'protecting', 'our', 'great', '2A', 'they', 'should', 'love', 'trump', '.', 'problem', 'is', 'i', 'beat', 'them', 'all', '!', '</s>']
[('<s>', 'most', 'of'), ('most', 'of', 'the'), ('of', 'the', 'money'), ('the', 'money', 'raised'), ('money', 'raised', 'by'), ('raised', 'by', 'the'), ('by', 'the', 'rino'), ('the', 'rino', 'losers'), ('rino', 'losers', 'of'), ('losers', 'of', 'the'), ('of', 'the', 'lincoln'), ('the', 'lincoln', 'project'), ('lincoln', 'project', 'goes'), ('project', 'goes', 'into'), ('goes', 'into', 'their'), ('into', 'their', 'own'), ('their', 'own', 'pockets'), ('own', 'pockets', '.'), ('pockets', '.', 'with'), ('.', 'with', 'what'), ('with', 'what', 'i'), ('what', 'i', 've'), ('i', 've', 'done'), ('ve', 'done', 'on'), ('done', 'on', 'judges'), ('on', 'judges', 'taxes'), ('judges', 'taxes', 'regulations'), ('taxes', 'regulations', 'healthcare'), ('regulations', 'healthcare', 'the'), ('healthcare', 'the', 'military'), ('the', 'military', 'vets'), ('military', 'vets', 'choice'), ('vets', 'choice', '!'), ('choice', '!', 'and'), ('!', 'and', ';'), ('and', ';', 'protecting'), (';', 'protecting', 'our'), ('protecting', 'our', 'great'), ('our', 'great', '2A'), ('great', '2A', 'they'), ('2A', 'they', 'should'), ('they', 'should', 'love'), ('should', 'love', 'trump'), ('love', 'trump', '.'), ('trump', '.', 'problem'), ('.', 'problem', 'is'), ('problem', 'is', 'i'), ('is', 'i', 'beat'), ('i', 'beat', 'them'), ('beat', 'them', 'all'), ('them', 'all', '!'), ('all', '!', '</s>')]

In [20]:
trigram_counts = defaultdict(Counter)
for tokens in df['tokens']:
    for token1, token2, token3 in zip(tokens[:-2], tokens[1:-1], tokens[2:]): 
        trigram_counts[(token1, token2)].update([token3]) # [token3] bc without [] it will update each character

trigram_counts[('<s>', 'Just')].most_common(10)

[]

In [10]:
probabilities = []
for candidate_word, count in bigram_counts["Just"].items():
    probabilities.append((candidate_word, count / word_counts["Just"]))

probabilities[:10]

[]

In [21]:
def bigram_model(init_seed = "<s>", finish_seed = "</s>", length = -1):
    current_word = init_seed
    sentence = []
    while (length == -1 or len(sentence) < length) and current_word != finish_seed:
        sentence.append(current_word)
        probabilities = []
        for candidate_word, count in bigram_counts[current_word].items():
            probabilities.append(count / word_counts[current_word])
        current_word = str(np.random.choice(list(bigram_counts[current_word].keys()), p=probabilities))
    return ' '.join(sentence)
bigram_model()

'<s> i only wish everyone including the money but abe lincoln republican party and shirts and the debate and ; olympic and p are losers mittromney'

In [22]:
probabilities = []
seed = ('<s>', 'Just')
for candidate_word , count in trigram_counts[('<s>', 'Just')].items():
    probabilities.append((candidate_word, count / bigram_counts[seed[0]][seed[1]]))

print(probabilities)
next_word = str(np.random.choice([word for word, prob in probabilities], p=[prob for word, prob in probabilities]))
print(next_word)

[]

ValueError: 'a' cannot be empty unless no samples are taken

In [23]:
def trigram_model(init_seed = ("<s>", ), finish_seed = "</s>", length = -1):
    current_words = init_seed
    sentence = [init_seed[0]]
    while (length == -1 or len(sentence) < length) and current_words[-1] != finish_seed:
        
        # if current words is a single word, we need to use bigram model to get the next word
        if(len(current_words) == 1):
            next_word = bigram_model(init_seed = current_words[0], finish_seed = finish_seed, length = 2)
            current_words = (current_words[0], next_word.split()[1])
            
        sentence.append(current_words[1])
        probabilities = []

        if current_words not in trigram_counts:
            break

        for candidate_word, count in trigram_counts[current_words].items():
            probabilities.append(count / bigram_counts[current_words[0]][current_words[1]])
        first_word, second_word = current_words
        next_word = np.random.choice(list(trigram_counts[(first_word, second_word)].keys()), p=probabilities)
        current_words = (second_word, str(next_word))
        
    return ' '.join(sentence)

trigram_model()

'<s> he would see that it was !'